
spring:
  profiles:
    active:
      - secret
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    #   globally_quoted_identifiers: true

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    defer-datasource-initialization: true

  data:
    redis:
      port: 6379
      host: localhost

  sql:
    init:
      mode: always

