
spring:
  profiles:
    active:
      - secret
  datasource:
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

