package com.techeer.fashioncloud.global.error;


import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum ErrorCode {
    // POST
    POST_NOT_FOUND(404, "POST NOT FOUND"),

    // LOOKBOOK
    LOOK_BOOK_NOT_FOUND(404, "LOOK BOOK NOT FOUND"),
    LOOK_BOOK_POST_NOT_FOUND(404, "LOOK BOOK POST NOT FOUND"),
    LOOK_BOOK_TITLE_DUPLICATED(400, "LOOK BOOK TITLE IS DUPLICATED"),

    // USER
    USER_NOT_FOUND(404, "USER NOT FOUND"),
    USER_SELF_FOLLOW(400, "SELF FOLLOW IS NOT ALLOWED"),
    USER_SELF_UNFOLLOW(400, "SELF UNFOLLOW IS NOT ALLOWED"),
    USER_ALREADY_FOLLOWED(400, "ALREADY FOLLOWED USER"),
    USER_NOT_FOLLOWED(400, "NOT FOLLOWED USER"),

    // LOCATION
    LOCATION_INVALID(400, "LOCATION IS INVALID"),
    COORDINATE_INVALID(400, "COORDINATE IS INVALID"),
    ADRRESS_NOT_FOUND(404, "ADDRESS DATA NOT FOUND"),

    // API
    API_PARSE_FAILED(500, "API PARSE FAILED"),
    API_BAD_REQUEST(400, "API_BAD_REQUEST"),
    API_SERVER_ERROR(500, "API_SERVER_ERROR"),

    // AUTH
    JWT_AUTHORITY_NOT_FOUND(403, "JWT TOKEN AUTHORITY NOT FOUND"),
    JWT_EXPIRED(401, "JWT TOKEN EXPIRED"),
    JWT_UNSUPPORTED(401, "UNSUPPORTED JWT TOKEN"),
    JWT_INVALID(401, "INVALID JWT TOKEN"),
    REFRESH_TOKEN_INVALID(400, "REFRESH TOKEN IS INVALID"),
    SIGNUP_EMAIL_DUPLICATED(400, "EMAIL ALREADY EXISTS"),

    // 서버
    INTERNAL_SERVER_ERROR(500, "INTERNAL SERVER ERROR"),

    // 공통
    PERMISSION_DENIED(403, "PERMISSION DENIED");


    private Integer status;
    private String message;
}
